## Abhishek Sharma
### CS 2nd Year | Section : "I" | Roll No.: 01

### Enrollment No.: 12019009001127

## Advanced Artificial Intelligence and Machine Learning Lab 8

#### Faculty : PB, MB, BM | Date : 13.04.2021

In [1]:
# SVD function 

from numpy import array
from scipy.linalg import svd
A =array([[1,2],[3,4],[5,6]])
print (A)
U, s, VT = svd (A)
print (U)
print (s)
print (VT)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [3]:
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from scipy.linalg import svd
A =array([[1,2],[3,4],[5,6]])
print (A)

U, s, VT = svd (A)
Sigma = zeros((A.shape[0], A.shape[1]))

Sigma [:A.shape[1], :A.shape[1]] = diag(s)

B = U.dot(Sigma.dot(VT))
print (B)

[[1 2]
 [3 4]
 [5 6]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [4]:
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from scipy.linalg import svd

A = array([[1,2,3],[4,5,6],[7,8,9]])
print (A)
U, s, VT = svd (A)

Sigma = diag(s)

B = U.dot(Sigma.dot(VT))
print (B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [5]:
from numpy import array
from numpy.linalg import pinv
A = array([[0.1,0.2], [0.3,0.4], [0.5,0.6]])

print (A)

B = pinv(A)
print (B)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]]
[[-13.33333333  -3.33333333   6.66666667]
 [ 10.83333333   3.33333333  -4.16666667]]


In [8]:
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from scipy.linalg import svd

A = array([
    [1,2,3,4,5,6,7,8,9,10],
    [11,12,13,14,15,16,17,18,19,20],
    [21,22,23,24,25,26,27,28,29,30]
])

print (A)
U, s, VT = svd (A)

Sigma = zeros((A.shape[0], A.shape[1]))

Sigma [:A.shape[0], :A.shape[0]] = diag(s)

n_elements = 2
Sigma = Sigma[:,:n_elements]
VT = VT[:n_elements, :]

B = U.dot(Sigma.dot(VT))

print (B)

T = U.dot(Sigma)
print (T)

T = A.dot(VT.T)
print (T)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


In [9]:
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from scipy.linalg import svd
from sklearn.decomposition import TruncatedSVD
A = array([
    [1,2,3,4,5,6,7,8,9,10],
    [11,12,13,14,15,16,17,18,19,20],
    [21,22,23,24,25,26,27,28,29,30]
])

svd = TruncatedSVD(n_components = 2)
svd.fit(A)

result = svd.transform(A)
print (result)

[[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]


In [10]:
print (A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
